[package]
name = "HW-Crypto-Tests"
version = "0.1.0"
edition = "2021"

[dependencies]
des = "0.8.1"
rand = "0.8.5"
serialport = "4.3.0"
clap = { version = "4.5.4", features = ["derive"] }
hex = "0.4.3"
regex = "1.10.4"
aes = "0.8.4"
