name: Rust Windows Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permission

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Archive build
      run: |
        mkdir -p artifacts
        cp target/release/HW-Crypto-Tests.exe artifacts/
        tar -czvf artifacts/HW-Crypto-Tests.zip -C artifacts HW-Crypto-Tests.exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: artifacts/HW-Crypto-Tests.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: .

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        artifacts: "./artifacts/HW-Crypto-Tests.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ github.ref }}
        body: "Automated release by GitHub Actions."
        draft: false
        prerelease: false
